language: ruby
script: 'bundle exec rake test'
rvm: 2.4.1

services:
  - postgresql

test:
  adapter: postgresql
  database: travis
  username: myapp
  encoding: utf8
  password: password1


before_script:
  - psql -c 'create database travis;' -U postgres
  - psql -c "CREATE USER myapp WITH PASSWORD 'password1';"
