language: ruby
script: 'bundle exec rake test'
rvm: 2.4.1

services:
  - postgresql

test:
  adapter: postgresql
  database: myapp
  username: myapp
  encoding: utf8
  password: password1


before_script:
  - psql -c 'create database myapp;' -U postgres
  - CREATE USER myapp WITH PASSWORD 'password1';
