# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1365ae183427727bbb0d5759d88a7794c3648edba3290ff37acabc865a88d5b15ca43fc10ecc2731207887bbab1678a3794f3dc0e6dd41c3b77d41d61e308119
  FRINGE_API_KEY: <%= ENV["FRINGE_API_KEY"] %>
  FRINGE_SECRET_KEY: <%= ENV["FRINGE_SECRET_KEY"] %>

test:
  secret_key_base: 43e2239a3a19e4486d100c2b05995f7a4ab9a08f2375bb595699f1e440ff288e1cc64f589e9cc7b20f9046ee67c3400c7c6f2dcdefce4efc8fc8ec8667cf3a3a
  FRINGE_API_KEY: <%= ENV["FRINGE_API_KEY"] %>
  FRINGE_SECRET_KEY: <%= ENV["FRINGE_SECRET_KEY"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  FRINGE_API_KEY: <%= ENV["FRINGE_API_KEY"] %>
  FRINGE_SECRET_KEY: <%= ENV["FRINGE_SECRET_KEY"] %>